# SPDX-FileCopyrightText: 2025 Konstantinas Mesnikas
#
# SPDX-License-Identifier: MIT

ignored:
  # DL3008: Pin versions in apt-get install
  # We use the latest versions from Debian stable
  - DL3008
  # DL3013: Pin versions in pip
  # We want the latest reuse tool
  - DL3013

failure-threshold: warning

override:
  error:
    - DL3002  # Last USER should not be root
    - DL3025  # Use JSON notation for CMD and ENTRYPOINT
  warning:
    - DL3009  # Delete apt-get cache
    - DL3015  # Avoid additional packages