coverage:
  precision: 2
  round: down
  range: "90...100"

  status:
    project:
      default:
        target: auto
        threshold: 0%
        if_ci_failed: error

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: false